create table players(
    id number generated by default as identity primary key,
    username varchar(30) not null,
    password varchar(30) not null,
    pozicion_rresht number,
    pozicion_kolone number,
    fillim_rresht number,
    fillim_kolone number,
    fund_rresht number,
    fund_kolone number,
    piket number,
    labirintiMatrice CLOB CHECK (labirintiMatrice IS JSON),
    piketVektor CLOB CHECK (piketVektor IS JSON),
    vektorCount number
);
